### ISSUE TITLE
设置save_render=True时,gym报错

### ISSUE THREAD

**Issue by JUNTING116** [Intelligent-Driving-Laboratory/GOPS#7]
当设置save_render = True时，执行run_idp_sac_dsac.py报错
*** Begin to run policy 1 ***
Create environment successfully!
Train space:
[[-5.  -0.1 -0.1 -0.3 -0.3 -0.3]
 [ 5.   0.1  0.1  0.3  0.3  0.3]]
Work space:
[[-5.  -0.1 -0.1 -0.3 -0.3 -0.3]
 [ 5.   0.1  0.1  0.3  0.3  0.3]]
Traceback (most recent call last):
  File "example_run/run_idp_sac_dsac.py", line 28, in <module>
    runner.run()
  File "e:\gops_test\gops\gops\sys_simulator\sys_run.py", line 959, in run
    self.__run_data()
  File "e:\gops_test\gops\gops\sys_simulator\sys_run.py", line 851, in __run_data
    eval_dict, tracking_dict = self.run_an_episode(
  File "e:\gops_test\gops\gops\sys_simulator\sys_run.py", line 178, in run_an_episode
    obs, info = env.reset(**init_info)
  File "E:\anaconda3\envs\gops\lib\site-packages\gym\wrappers\record_video.py", line 58, in reset
    self.start_video_recorder()
  File "E:\anaconda3\envs\gops\lib\site-packages\gym\wrappers\record_video.py", line 75, in start_video_recorder
    self.video_recorder.capture_frame()
  File "E:\anaconda3\envs\gops\lib\site-packages\gym\wrappers\monitoring\video_recorder.py", line 157, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "E:\anaconda3\envs\gops\lib\site-packages\gym\core.py", line 286, in render
    return self.env.render(mode, **kwargs)
  File "E:\anaconda3\envs\gops\lib\site-packages\gym\core.py", line 286, in render
    return self.env.render(mode, **kwargs)
  File "E:\anaconda3\envs\gops\lib\site-packages\gym\core.py", line 286, in render
    return self.env.render(mode, **kwargs)
  [Previous line repeated 2 more times]
  File "e:\gops_test\gops\gops\env\env_ocp\pyth_idpendulum.py", line 143, in render
    image_from_plot = image_from_plot.reshape(
ValueError: cannot reshape array of size 1440000 into shape (480,640,3)

**Comment by yangyujie-jack** [comment]
Thank you for raising this problem. This problem appears because matplotlib uses a backend that we do not support on Windows (probably "QtAgg"). We have fixed it by explicitly setting the backend to "Agg" in [pyth_idpendulum.py L22](https://github.com/Intelligent-Driving-Laboratory/GOPS/blob/c7ee85a834a68259f55782bc574ee488a37d92fe/gops/env/env_ocp/pyth_idpendulum.py#L22).
